name: 'Summary coverage check'
description: 'creates a check with link to coverage report url'
inputs:
  coverage-file:
    description: summary coverage json file (glob)
    required: true
  coverage-mode:
    description: which type of coverage is reported (branches, functions, statements, lines)
    default: 'branches'
    required: false
  github-token:
    description: github token for octokit
    required: true
  report-url:
    description: url to detailed coverage report
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
