name: 'Summary coverage check'
description: 'creates a check with link to coverage report url'
inputs:
  coverage-file:
    description: Coverage file to parse
    required: true
  coverage-format:
    description: format of the coverage file (istanbul, summary)
    default: 'istanbul'
    required: false
  coverage-mode:
    description: which type of coverage is reported (branches, functions, statements, lines)
    default: 'branches'
    required: false
  github-token:
    description: github token for octokit
    required: true
  report-url:
    description: url to detailed coverage report
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
