name: Build
on:
  workflow_call:

jobs:
  test-jest:
    runs-on: ubuntu-latest
    name: Test (Jest)
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm
      - run: npm ci
      - run: npm run test
  test-action:
    runs-on: ubuntu-latest
    name: Test (GitHub Actions)
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm
      - run: npm ci
      - run: npm run bundle
      - run: npm run test -- --coverage --coverage-reporters=json
      - uses: ./
        with:
          coverage-file: coverage/coverage-final.json
          report-url: 'https://github.com/smartlyio/summary-coverage-action'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-mode: lines
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm
      - run: npm ci
      - run: npm run lint
  prettier:
    runs-on: ubuntu-latest
    name: Prettier
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm
      - run: npm ci
      - run: npm run format:check
  typecheck:
    runs-on: ubuntu-latest
    name: Typecheck
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm
      - run: npm ci
      - run: npm run typecheck
