name: Pull Request

on: pull_request

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit

  release:
    needs: [build]
    runs-on: ubuntu-latest
    name: Release (dry-run)
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Configure git
        uses: smartlyio/github-actions@git-init-userinfo-v1
      - name: Release flow
        uses: smartlyio/github-actions@release-action-node-v1
        with:
          dry_run: true
          token: '${{ secrets.GITHUB_TOKEN }}'
