name: Release

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit

  publish:
    runs-on: ubuntu-latest
    name: Publish
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Configure git
        uses: smartlyio/github-actions@git-init-userinfo-v1
      - name: Release flow
        uses: smartlyio/github-actions@release-action-node-v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
