name: Release

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit

  publish:
    runs-on: ubuntu-latest
    name: Publish
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Configure git
        uses: smartlyio/github-actions@4ef49912877febb62867891d42a1205190fb2ab0 # git-init-userinfo-v1
      - name: Release flow
        uses: smartlyio/github-actions@ac9cc7e148b55d6c88641ea387ab6d2860ba5c3e # release-action-node-v1
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
